import { Routes } from '@angular/router';
import { ShellComponent } from './layout';
import { LoginComponent } from './features/auth/login/login.component';
import { authGuard } from './core/guards/auth.guard';
import { roleGuard } from './core/rbac/role.guard';
import { Role } from './core/rbac/role.enum';
import {
  DashboardComponent,
  StudentsComponent,
  StudentFormComponent,
  StudentDetailsComponent,
  InstructorsListComponent,
  InstructorFormComponent,
  InstructorDetailsComponent,
  ClassGroupsComponent,
  ClassGroupFormComponent,
  EnrollmentsComponent,
  EnrollmentFormComponent,
  AttendanceComponent,
  SessionsComponent,
  SessionFormComponent,
  ObjectivesComponent,
  ObjectiveFormComponent,
  ObjectiveDetailsComponent,
  EvaluationsComponent,
  EvaluationFormComponent,
  EvolutionsComponent,
  EvolutionFormComponent,
  DailyAgendaComponent,
  MakeupApprovalComponent,
} from './pages';

export const routes: Routes = [
  { path: 'login', component: LoginComponent },
  {
    path: '',
    component: ShellComponent,
    canActivate: [authGuard],
    children: [
      { path: 'dashboard', component: DashboardComponent, canActivate: [roleGuard], data: { roles: [Role.ADMIN, Role.OWNER] } },
      { path: 'students', component: StudentsComponent, canActivate: [roleGuard], data: { roles: [Role.ADMIN, Role.RECEPTIONIST] } },
      { path: 'students/new', component: StudentFormComponent, canActivate: [roleGuard], data: { roles: [Role.ADMIN, Role.RECEPTIONIST] } },
      { path: 'students/:id', component: StudentDetailsComponent, canActivate: [roleGuard], data: { roles: [Role.ADMIN, Role.RECEPTIONIST] } },
      { path: 'students/:id/edit', component: StudentFormComponent, canActivate: [roleGuard], data: { roles: [Role.ADMIN, Role.RECEPTIONIST] } },
      { path: 'instructors', component: InstructorsListComponent, canActivate: [roleGuard], data: { roles: [Role.ADMIN] } },
      { path: 'instructors/new', component: InstructorFormComponent, canActivate: [roleGuard], data: { roles: [Role.ADMIN] } },
      { path: 'instructors/:id', component: InstructorDetailsComponent, canActivate: [roleGuard], data: { roles: [Role.ADMIN] } },
      { path: 'instructors/:id/edit', component: InstructorFormComponent, canActivate: [roleGuard], data: { roles: [Role.ADMIN] } },
      { path: 'class-groups', component: ClassGroupsComponent, canActivate: [roleGuard], data: { roles: [Role.ADMIN] } },
      { path: 'class-groups/new', component: ClassGroupFormComponent, canActivate: [roleGuard], data: { roles: [Role.ADMIN] } },
      { path: 'class-groups/:id', component: ClassGroupFormComponent, canActivate: [roleGuard], data: { roles: [Role.ADMIN] } },
      { path: 'class-groups/:id/edit', component: ClassGroupFormComponent, canActivate: [roleGuard], data: { roles: [Role.ADMIN] } },
      { path: 'enrollments', component: EnrollmentsComponent, canActivate: [roleGuard], data: { roles: [Role.ADMIN, Role.RECEPTIONIST] } },
      { path: 'enrollments/new', component: EnrollmentFormComponent, canActivate: [roleGuard], data: { roles: [Role.ADMIN, Role.RECEPTIONIST] } },
      { path: 'enrollments/:id/edit', component: EnrollmentFormComponent, canActivate: [roleGuard], data: { roles: [Role.ADMIN, Role.RECEPTIONIST] } },
      { path: 'attendance', component: AttendanceComponent, canActivate: [roleGuard], data: { roles: [Role.ADMIN, Role.RECEPTIONIST, Role.INSTRUCTOR] } },
      { path: 'daily-agenda', component: DailyAgendaComponent, canActivate: [roleGuard], data: { roles: [Role.ADMIN, Role.RECEPTIONIST, Role.INSTRUCTOR] } },
      { path: 'sessions', component: SessionsComponent, canActivate: [roleGuard], data: { roles: [Role.ADMIN, Role.RECEPTIONIST, Role.INSTRUCTOR] } },
      { path: 'sessions/new', component: SessionFormComponent, canActivate: [roleGuard], data: { roles: [Role.ADMIN, Role.RECEPTIONIST, Role.INSTRUCTOR] } },
      { path: 'sessions/:id/edit', component: SessionFormComponent, canActivate: [roleGuard], data: { roles: [Role.ADMIN, Role.RECEPTIONIST, Role.INSTRUCTOR] } },
      { path: 'makeup-approval', component: MakeupApprovalComponent, canActivate: [roleGuard], data: { roles: [Role.ADMIN, Role.RECEPTIONIST] } },
      { path: 'objectives', component: ObjectivesComponent, canActivate: [roleGuard], data: { roles: [Role.INSTRUCTOR, Role.ADMIN] } },
      { path: 'objectives/new', component: ObjectiveFormComponent, canActivate: [roleGuard], data: { roles: [Role.INSTRUCTOR, Role.ADMIN] } },
      { path: 'objectives/:id', component: ObjectiveDetailsComponent, canActivate: [roleGuard], data: { roles: [Role.INSTRUCTOR, Role.ADMIN] } },
      { path: 'objectives/:id/edit', component: ObjectiveFormComponent, canActivate: [roleGuard], data: { roles: [Role.INSTRUCTOR, Role.ADMIN] } },
      { path: 'evaluations', component: EvaluationsComponent, canActivate: [roleGuard], data: { roles: [Role.INSTRUCTOR, Role.ADMIN] } },
      { path: 'evaluations/new', component: EvaluationFormComponent, canActivate: [roleGuard], data: { roles: [Role.INSTRUCTOR, Role.ADMIN] } },
      { path: 'evaluations/:id/edit', component: EvaluationFormComponent, canActivate: [roleGuard], data: { roles: [Role.INSTRUCTOR, Role.ADMIN] } },
      { path: 'evolutions', component: EvolutionsComponent, canActivate: [roleGuard], data: { roles: [Role.INSTRUCTOR, Role.ADMIN] } },
      { path: 'evolutions/new', component: EvolutionFormComponent, canActivate: [roleGuard], data: { roles: [Role.INSTRUCTOR, Role.ADMIN] } },
      { path: 'evolutions/:id/edit', component: EvolutionFormComponent, canActivate: [roleGuard], data: { roles: [Role.INSTRUCTOR, Role.ADMIN] } },
      { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
    ],
  },
];
